# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-22 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MRA', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='parts',
            name='id',
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(verbose_name=b'hire date'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='unit_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='parts',
            name='part_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
