# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-28 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MRA', '0002_auto_20160922_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Lockout',
            fields=[
                ('lock_out_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Parts_Units',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('skills_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('unit_number_id', models.IntegerField(primary_key=True, serialize=False)),
                ('unit_number', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('install_date', models.DateField(null=True, verbose_name=b'installation date')),
                ('pid_number', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Work_Order',
            fields=[
                ('work_order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('priority_level', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=500)),
                ('status', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField(verbose_name=b'start date')),
                ('close_date', models.DateTimeField(verbose_name=b'close date')),
            ],
        ),
        migrations.CreateModel(
            name='Work_Order_Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MRA.Unit')),
                ('work_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MRA.Work_Order')),
            ],
        ),
        migrations.RenameField(
            model_name='parts',
            old_name='part_number',
            new_name='parts_id',
        ),
        migrations.RemoveField(
            model_name='parts',
            name='equipment',
        ),
        migrations.AddField(
            model_name='employee',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='parts',
            name='description',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parts',
            name='location',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parts',
            name='quantity_on_hand',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(null=True, verbose_name=b'hire date'),
        ),
        migrations.DeleteModel(
            name='Equipment',
        ),
        migrations.AddField(
            model_name='work_order',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MRA.Employee'),
        ),
        migrations.AddField(
            model_name='work_order',
            name='lock_out_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MRA.Lockout'),
        ),
        migrations.AddField(
            model_name='parts_units',
            name='parts_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MRA.Parts'),
        ),
        migrations.AddField(
            model_name='parts_units',
            name='unit_number_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MRA.Unit'),
        ),
        migrations.AddField(
            model_name='lockout',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MRA.Employee'),
        ),
        migrations.AddField(
            model_name='employee_skills',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MRA.Employee'),
        ),
        migrations.AddField(
            model_name='employee_skills',
            name='skills_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MRA.Skills'),
        ),
    ]
