# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-30 12:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MRA', '0003_auto_20160928_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(default=datetime.datetime(2016, 9, 30, 12, 14, 51, 179000, tzinfo=utc), verbose_name=b'hire date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='title',
            field=models.CharField(default='newb', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unit',
            name='install_date',
            field=models.DateField(default=datetime.datetime(2016, 9, 30, 12, 15, 29, 76000, tzinfo=utc), verbose_name=b'installation date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unit',
            name='pid_number',
            field=models.CharField(default='-', max_length=100),
            preserve_default=False,
        ),
    ]
